### ISSUE TITLE
Support Java 8

### ISSUE THREAD

**Issue by MGelbana-Incorta** [onelogin/onelogin-java-sdk#11]
Specify the Java source and target versions as 1.8 in maven's pom.xm file.

**Comment by pitbulk** [comment]
I think the SDK is compatible with Java 7 and Java 8. isn't it?

**Comment by MGelbana-Incorta** [comment]
Yes but the pom file doesn't specify Java 8 as the source and target versions. So in Eclipse, I can't use streams or lambda expressions. Please correct me if I missed anything.

**Comment by pitbulk** [comment]
I'm not a java guru, but what prevents you to specify it in your pom version to satisfy the specific Eclipse needs you have?

**Comment by MGelbana-Incorta** [comment]
Well the `pom.xml` file affects how Eclipse is configured. And currently, it doesn't specify a Java version which defaults to Java 1.5 on Eclipse. That's a VERY old version.

On the other hand, if I specify the Java version in Eclipse to be anything and not reflect the same change in the `pom.xml`, I'll end up writing code that doesn't compile on someone else's machine.

The other important effect of specifying Java 8 as the minimum version is that customers won't be able to use this client while running on a Java runtime versions earlier than Java 8.

Java 7 is [considered way outdated](https://java.com/en/download/faq/java_7.xml) and Java 8 usage is encouraged now.

Is it ok to upgrade to Java 8 now to leverage it's features ?

**Comment by pitbulk** [comment]
We have customers using Java 7 and sadly we can't force them to move to Java 8

**Comment by MGelbana-Incorta** [comment]
That's good to know. Then at least we can increase the level to Java 7 ?

**Comment by pitbulk** [comment]
I think so, 

On the [java-saml](https://github.com/onelogin/java-saml) repository we have the following:
* [.java-version](https://github.com/onelogin/java-saml/blob/master/.java-version) file
* [requireJavaVersion](https://github.com/onelogin/java-saml/blob/master/pom.xml#L80) in pom.xml

do you have a PR?

**Comment by MGelbana-Incorta** [comment]
I'll do that soon. As I'm working on batching.

**Comment by MGelbana-Incorta** [comment]
Settled on using Java 1.7
