### ISSUE TITLE
Allow specifying Client ID, secret and region through the API

### ISSUE THREAD

**Issue by MGelbana-Incorta** [onelogin/onelogin-java-sdk#14]
Currently the only way to set the client ID, secret and region is through the `onelogin.sdk.properties` file put on top of the classpath.

This makes it hard (impossible without class loading tricks ?) to have multiple client instances with different credentials in the same JVM.

**Comment by pitbulk** [comment]
We can create a new constructor for Settings to be able to accept those value via method parameter, and do the same for Client, accepting also those parameters and use the new Settings constructor.

**Comment by MGelbana-Incorta** [comment]
[PR](https://github.com/onelogin/onelogin-java-sdk/pull/15) created.
