### ISSUE TITLE
Logging implementation should NOT be compile scope

### ISSUE THREAD

**Issue by scottcarey** [onelogin/onelogin-java-sdk#18]
https://github.com/onelogin/onelogin-java-sdk/blob/37a71352223948eb0a4075e3a504f40f90ba05c4/pom.xml#L71

Logging implementations should NOT be in compile scope.  The API jar (slf4j) should be in compile scope, while the implementation (logback) should be `<optional>true</optional>` or provided scope.

Otherwise, any downstream user will have to manually exclude your logging implementation choice if they want to use any of the others out there.

This may also affect the java-saml jar, I know for sure it affects onelogin-java-sdk

**Comment by pitbulk** [comment]
I will review and fix it. Thanks for reporting.

**Comment by pitbulk** [comment]
For clarification, are you asking to change at [onelogin-java-sdk/pom.xml](https://github.com/onelogin/onelogin-java-sdk/blob/master/pom.xml#L69)

```
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.0</version>
</dependency>
```
by
```    
<dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.0</version>
      <scope>provided</scope>
</dependency>
``` 

As well as [java-saml/pom.xml](https://github.com/onelogin/java-saml/blob/master/pom.xml#L54) 
```
<dependency>
	<groupId>ch.qos.logback</groupId>
	<artifactId>logback-classic</artifactId>
	<version>${logbackVersion}</version>
</dependency>
```
by
```

<dependency>
	<groupId>ch.qos.logback</groupId>
	<artifactId>logback-classic</artifactId>
	<version>${logbackVersion}</version>
	<scope>provided</scope>
</dependency>
```

**Comment by scottcarey** [comment]
The two options are `<scope>provided</scope>` and `<optional>true</optional>`.   Libraries tend to use `<optional>true</optional>` more often, and it is common for the logging implementation use case.   It more cleanly terminates the transitive dependencies and would mean that I  never see the logback dependency as a user of your library, even at compile time.

`<scope>provided</scope>` is more often used for applications to manage other dependencies from within.  It would mean that I may see it in some classpaths, but will not have it packaged into any final artifacts.

Either will work for this case from my perspective, but optional is preferred.

https://stackoverflow.com/questions/40393098/when-to-use-optionaltrue-optional-and-when-to-use-scopeprovided-scope

http://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by pitbulk** [comment]
Ok thanks for clarification. I will implement then the optional.
