### ISSUE TITLE
Authenticate with SSO Identity Provider

### ISSUE THREAD

**Issue by bigalnz** [onelogin/onelogin-java-sdk#24]
Hi,

Is this the correct library to use if I want to authenticate with a SAML2 SSO identity provider? (ie write the code to be a client)

Cheers

Al

**Comment by pitbulk** [comment]
Yes.

**Comment by bigalnz** [comment]
Do you have a client example? It's SAP with username and password.

**Comment by pitbulk** [comment]
oh sorry, the right repository is: https://github.com/onelogin/java-saml
you can find an example at https://github.com/onelogin/java-saml/tree/master/samples/java-saml-tookit-jspsample

**Comment by bigalnz** [comment]
Ahh, I see that is a JSP example. Is there a example that uses native Java?

**Comment by pitbulk** [comment]
The code you find inside the JSP example and generate/process the SAML Messages is "native" Java code.
