### ISSUE TITLE
User model "groupId" Data Type "long" expected to be "Integer"

### ISSUE THREAD

**Issue by Ak4uma** [onelogin/onelogin-java-sdk#29]
Hello, I am facing the error while using the library "‘group_id has incorrect data type. It should be -> integer’"
Changing the model manually to int seems to remove the error, and the code would run, is there a possibility of fixing this, or am I mistaken about this being an issue? 

https://github.com/onelogin/onelogin-java-sdk/blob/6c566b33b480d5b074d228b3cef4be98c61c6df3/src/main/java/com/onelogin/sdk/model/User.java#L30

Thank you for reading.

**Comment by pitbulk** [comment]
At the User and Group model, the groupId is managed as Long.
Is possible that other endpoints manage it as an Integer, you will need to parse it from Integer to Long.

**Comment by Jmfwolf** [comment]
This issue has been resolved, I am going to close it.
