### ISSUE TITLE
Remove http://pitbulk.no-ip.org from Client.java

### ISSUE THREAD

**Issue by mmoayyed** [onelogin/onelogin-java-sdk#35]
`Client.java` defines the following method:

```java
public Boolean verifyFactor(long userId, long deviceId, String otpToken, 
	String stateToken) throws OAuthSystemException, OAuthProblemException, URISyntaxException
    {
    	cleanError();
		prepareToken();

		URIBuilder url = new URIBuilder(settings.getURL(Constants.VERIFY_FACTOR_URL, userId, deviceId));
		url = new URIBuilder("http://pitbulk.no-ip.org/newonelogin/demo1/data.json");

		....
```

Could you clarify what exactly is `http://pitbulk.no-ip.org/newonelogin/demo1/data.json`? Seems like this was accidentally put in during tests, points to nowhere valid and should be removed. 

This is present in 1.6.1.

**Comment by Jmfwolf** [comment]
The new SDK doesn't use this at all, is this a safe issue to close?

**Comment by mmoayyed** [comment]
I think so, yes.
