### ISSUE TITLE
The response was received at http:// instead of https://

### ISSUE THREAD

**Issue by jellson1998** [onelogin/onelogin-java-sdk#4]
Hi All,

Can some one help?  I am authenticating via onelogin and ADFS.. According to ADFS I am authenticating successfully but getting the error:

The response was received at http://myurl/BORAUTH/acs.jsp instead of https://myurl/BORAUTH/acs.jsp

There is an F5 load balancer that the myurl resolves to.

Thank you!

**Comment by pitbulk** [comment]
Wrong repo
