### ISSUE TITLE
Client.getEventTypes does not support HTTP proxy system properties

### ISSUE THREAD

**Issue by grossedouceur** [onelogin/onelogin-java-sdk#42]
The issue can be reproduced in an environment that is behind an HTTP Proxy.

If I launch a Java program using this SDK with the [HTTP proxy system properties](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html) I can access every resources but [Event Types](https://developers.onelogin.com/api-docs/1/events/event-types).

I suppose it is because Event Types does not requires authentication and the SDK uses, in that case, a [default HttpClient](https://github.com/onelogin/onelogin-java-sdk/blob/master/src/main/java/com/onelogin/sdk/conn/Client.java#L1922) instead of one using the [system properties](https://www.javadoc.io/static/org.apache.httpcomponents/httpclient/4.5.1/org/apache/http/impl/client/HttpClients.html#createSystem()).

**Comment by Jmfwolf** [comment]
Hey grossedouceur,
I am the new guy assigned to our public SDK repos. I am working on resolving your issue, I appreciate your patience in the process.

**Comment by Jmfwolf** [comment]
Please try the latest release. It has taken a bit, but I came around
