### ISSUE TITLE
missing state value

### ISSUE THREAD

**Issue by atomz4peace** [onelogin/onelogin-java-sdk#5]
It looks like the user object is not pulling the "state" attribute. Is that intentional or just didn't get in there yet?

**Comment by pitbulk** [comment]
Is missing, as well as the [Set User State](https://developers.onelogin.com/api-docs/1/users/set-state)

When I implemented the SDK, user's state was not part of the API and I have not updated the SDK

**Comment by pitbulk** [comment]
Added https://github.com/onelogin/onelogin-java-sdk/commit/ed3c74ef100f986a3b78e41767dd441b96d35662
