### ISSUE TITLE
Incorrect attribute name "subodmain" in class CreateSessionLoginTokenRequest 

### ISSUE THREAD

**Issue by zvillafuertesalvador** [onelogin/onelogin-java-sdk#55]
I am using the api and I always get the 401 error when invoke /api/1/login/auth.

checking the subodmain attribute is wrong, it should be: subdomain

**Comment by eriktalvi** [comment]
Which version are you using? 3.0.1?

**Comment by zvillafuertesalvador** [comment]
> Which version are you using? 3.0.1?
Yes, I am using the version 3.0.1.

**Comment by eriktalvi** [comment]
On list to fix.

**Comment by Jmfwolf** [comment]
Naming was fixed on the latest version, please let me know if you have any more issues with it
