### ISSUE TITLE
NPE in Client.getRoles

### ISSUE THREAD

**Issue by bbaumgartner** [onelogin/onelogin-java-sdk#6]
Hello

Given:
        Client client = new Client();
        List<Role> roles = client.getRoles();
Results in:
java.lang.NullPointerException: null
	at com.onelogin.sdk.conn.Client.getRoles(Client.java:1343) ~[onelogin-java-sdk-1.1.0.jar:na]
	at com.onelogin.sdk.conn.Client.getRoles(Client.java:1373) ~[onelogin-java-sdk-1.1.0.jar:na]
	at com.onelogin.sdk.conn.Client.getRoles(Client.java:1410) ~[onelogin-java-sdk-1.1.0.jar:na]

skd version 1.1.0

This is the body of the response I receive:
{  
   "status":{  
      "error":false,
      "code":200,
      "type":"success",
      "message":"Success"
   },
   "pagination":{  
      "before_cursor":null,
      "after_cursor":null,
      "previous_link":null,
      "next_link":null
   },
   "data":[  
      {  
         "id":207213,
         "name":"Default"
      },
      {  
         "id":207221,
         "name":"Comerge Employee"
      },
      {  
         "id":208963,
         "name":"Comerge Geschäftsleitung"
      },
      {  
         "id":210685,
         "name":"Comerge Teamleiter"
      }
   ]
}

I'm using a plain springboot 2.0 application generated with https://start.spring.io/

Best Regards
Benno

**Comment by pitbulk** [comment]
Can you modify the code as follows.

Replace:
```
afterCursor = oAuthResponse.getAfterCursor();
if (afterCursor == "null") {
    afterCursor = null;
} else if (!afterCursor.isEmpty()) {
    url.setParameter("after_cursor", oAuthResponse.getAfterCursor());
    bearerRequest.setLocationUri(url.toString());
}
``` 
by
```
afterCursor = oAuthResponse.getAfterCursor();
if (afterCursor != null && !afterCursor.isEmpty()) {
    url.setParameter("after_cursor", oAuthResponse.getAfterCursor());
    bearerRequest.setLocationUri(url.toString());
}
```

**Comment by pitbulk** [comment]
Fixed https://github.com/onelogin/onelogin-java-sdk/commit/96616ea856d9a73954e3d0b0f938553b73ea41c3
