### ISSUE TITLE
Missing app_id filter in usersV2Api.listUsers2

### ISSUE THREAD

**Issue by tprus** [onelogin/onelogin-java-sdk#63]
Please add app_id filter field to this method as it is in this request https://developers.onelogin.com/api-docs/2/users/list-users
It should be easy - is there chance You deliver it in short time?
Best regards!
Tomek

**Comment by Jmfwolf** [comment]
Please let me know how the newest release works for you, both issues have been addressed in this release:
https://github.com/onelogin/onelogin-java-sdk/releases/tag/3.1.2

**Comment by tprus** [comment]
Main issue is resolved, thanks!  You should also change version in pom to 3.1.2. Second issue still not working.
